all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_pass: 
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    

zookeeper:
  hosts:
    centos01.cluster.local:
    centos02.cluster.local:
    centos03.cluster.local:        

kafka_broker:
  hosts:
    centos01.cluster.local:
    centos02.cluster.local:
    centos03.cluster.local:        

schema_registry:
  hosts:
    centos04.cluster.local:

ksql:
  hosts:
    centos05.cluster.local:

kafka_connect:
  hosts:
    centos06.cluster.local:
      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    centos07.cluster.local:
