---
### Validates that GSSAPI protocol is set on Cluster2.
### Validates that MDS is HTTP on Cluster1 (MDS).
### Validates that all components on Cluster2 are pointing to the MDS on Cluster1.

- name: Verify - kafka_broker
  hosts: kafka_broker2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.metadata.sasl.mechanism
        expected_value: GSSAPI

- name: Verify - schema_registry
  hosts: schema_registry2
  gather_facts: false
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://mds-kafka-broker" /etc/schema-registry/schema-registry.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 0

- name: Verify - kafka_connect
  hosts: kafka_connect2
  gather_facts: false
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://mds-kafka-broker" /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 0

- name: Verify - kafka_rest
  hosts: kafka_rest2
  gather_facts: false
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://mds-kafka-broker" /etc/kafka-rest/kafka-rest.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 0

- name: Verify - ksql
  hosts: ksql2
  gather_facts: false
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://mds-kafka-broker" /etc/ksqldb/ksql-server.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center2
  gather_facts: false
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://mds-kafka-broker" /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 0
