---
- name: Get Kafka Cluster ID from Embedded Rest Proxy
  uri:
    url: "{{mds_http_protocol}}://{{ hostvars[groups['kafka_broker'][0]] | confluent.platform.resolve_hostname }}:{{mds_port}}/kafka/v3/clusters"
    method: GET
    validate_certs: false
    body_format: json
    return_content: true
    status_code: 200
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    force_basic_auth: true
  register: cluster_id_query
  until: cluster_id_query.status == 200
  retries: 5
  delay: 10
  when: cluster_id_source | default('erp') == 'erp'

- name: Parse Kafka Cluster ID from json query
  set_fact:
    kafka_cluster_id: "{{ cluster_id_query.json.data[0].cluster_id }}"
  when: (cluster_id_source | default('erp') == 'erp') and not ansible_check_mode

- name: Get Kafka Cluster ID from Zookeeper
  shell: >
      {{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{zookeeper_client_port}} \
      {% if zookeeper_ssl_enabled|bool %}-zk-tls-config-file {{ kafka_broker.zookeeper_tls_client_config_file \
      if kafka_broker_secrets_protection_enabled else kafka_broker.config_file }}{% endif %} \
      get /cluster/id | grep version
  register: zk_cluster_id_query
  when: cluster_id_source | default('erp') == 'zookeeper'

- set_fact:
    cluster_id_json: "{{ zk_cluster_id_query.stdout }}"
  when: cluster_id_source | default('erp') == 'zookeeper'

- name: Set kafka_cluster_id Variable
  set_fact:
    kafka_cluster_id: "{{ cluster_id_json.id }}"
  when: cluster_id_source | default('erp') == 'zookeeper'

- name: Create SSL Certificate Directory
  file:
    path: "{{ ssl_file_dir_final }}"
    state: directory
    mode: 0755
  when: copy_certs | default(True)
  tags:
    - privileged
    - filesystem

- name: Copy in MDS Public Pem File
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: 0640
    owner: "{{user}}"
    group: "{{group}}"
  when: copy_certs | default(True)
  diff: "{{ not mask_sensitive_diff|bool }}"
