---

- name: Kafka broker group
  group:
    name: "{{ kafka_broker.group }}"

- name: Kafka Broker user
  user:
    name: "{{ kafka_broker.user }}"
    comment: "Kafka User"
    system: true
    group: "{{ kafka_broker.group }}"

- name: Create kafka broker data directories
  file:
    path: "{{ item }}"
    owner: "{{ kafka_broker.user }}"
    group: "{{ kafka_broker.group }}"
    state: directory
    mode: 0755
  with_items: "{{ kafka_broker.datadir }}"

- name: Create logs directory
  file:
    path: "{{ kafka_broker.appender_log_path }}"
    group: "{{ kafka_broker.group }}"
    owner: "{{ kafka_broker.user }}"
    mode: '764'
    state: directory

- name: Add all hosts kafka clusters in file /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_all_ipv4_addresses'][0] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items:
    - "{{ groups['kafka_broker'] }}"
  failed_when: false

- name: Set file limits to user {{ kafka_broker.user }}
  template:
    src: kafka-nofiles.conf.j2
    dest: /etc/security/limits.d/kafka-nofiles.conf
