---
name: Linting
on: [push, pull_request]
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container: cytopia/ansible-lint:5
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Ansible Lint code
        run: ansible-lint -c .ansible-lint -qq --force-color *.yml
  yamllint:
    name: Yaml Lint
    runs-on: ubuntu-latest
    container: cytopia/yamllint:latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yamllint code
        run: yamllint -c .yamllint -f colored .
