---

- name: start kafka
  systemd:
    name: "{{ kafka_broker.service_name }}"
    state: started
    daemon_reload: true

- name: reload systemd
  systemd:
    daemon_reload: true
- name: restart kafka
  systemd:
    name: "{{ kafka_broker.service_name }}"
    state: restarted
