---
- name: Find Property in File
  shell: "egrep '^{{property}}[ ]?=' {{file_path}}"
  register: grep
  changed_when: false

- name: Assert property set as expected
  assert:
    that:
      - expected_value == grep.stdout | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1')
    fail_msg: "Property: {{property}} set to {{ grep.stdout | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1') }} not {{expected_value}}"
