---
- name: Validate TLS Version on Port {{service_port}}
  shell: "openssl s_client -connect localhost:{{service_port}} -tls1 -CAfile {{service_ca}} -cert {{service_cert}} -key {{service_key}}"
  register: tls_response
  failed_when: tls_response.rc == 0
  changed_when: false

- name: Assert TLS 1 is not supported on Port {{service_port}}
  assert:
    that:
      - tls_response.rc == 1
    fail_msg: "A version of TLS less then 1.2 was accepted by port {{service_port}}"
    quiet: true
