---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - import_role:
        name: variables

    - name: Delete Tar Jar
      file:
        state: absent
        path: "{{ confluent_archive_file_source }}"

    - name: Delete Tar CLI
      file:
        state: absent
        path: "{{ confluent_cli_archive_file_source }}"
