---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Create Custom Group
      group:
        name: "{{archive_group}}"

    - name: Create Custom User
      user:
        name: "{{archive_owner}}"
