---

# vars defaults zookeeper
path_zoo: /etc/zookeeper
version_zoo: 3.8.0
init_limit_zoo: 5
sync_limit_zoo: 2
client_port_zoo: 2181
data_dir_zoo: /var/lib/zookeeper
log_dir_zoo: /var/log/zookeeper
open_file_limit: 500000
# this variable will be ignored if zookeeper group is bigger than  1
zookeeper_id: 1

# links for download to zookeeper
_zookeeper_link: https://downloads.apache.org/zookeeper/zookeeper-{{ version_zoo }}/apache-zookeeper-{{ version_zoo }}-bin.tar.gz
zookeeper_open_file_limit: "{{open_file_limit}}"

zookeeper_service_environment_overrides:
  JVMFLAGS: "-Xmx3g"
  ZOO_LOG_DIR: "{{ log_dir_zoo }}"

zookeeper_service_overrides:
  LimitNOFILE: "{{zookeeper_open_file_limit}}"

zookeeper:
  user: zookeeper
  group: zookeeper
  config_file: "{{ path_zoo }}/zoo.cfg"
  log_path: "{{ log_dir_zoo }}"
  max_log_files: 10
  log_file_size: 100MB
  service_name: zookeeper
  systemd_file: /usr/lib/systemd/system/zookeeper.service
  systemd_override: /etc/systemd/system/zookeeper.service.d
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    clientPort: "{{ client_port_zoo }}"
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: "{{ data_dir_zoo }}"
  systemd:
    enabled: true
    state: started
