---
- name: Check user on service
  shell: "ps aux|grep '{{user}}'"
  register: ps
  changed_when: false

- name: Assert user set as expected
  assert:
    that:
      - user == ps.stdout.split(' ')[0]
    fail_msg: "User: {{user}} set to {{ps.stdout.split(' ')[0]}} not {{user}}"
