---
- name: Check group membership
  shell: "grep {{user}} /etc/group"
  register: group_member
  changed_when: false

- name: Assert user set as expected
  assert:
    that:
      - group == group_member.stdout.split(':')[0]
    fail_msg: "User: {{group}} set to {{group_member.stdout.split(':')[0]}} not {{group}}"
