---
- name: Zookeeper Provisioning
  hosts: zookeeper
  tags: zookeeper
  tasks:
    - include_role:
        name: confluent.zookeeper
        tasks_from: health_check.yml

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags: kafka_broker
  tasks:
    - include_role:
        name: confluent.kafka_broker
        tasks_from: health_check.yml

- name: Schema Registry Provisioning
  hosts: schema_registry
  tags: schema_registry
  tasks:
    - include_role:
        name: confluent.schema_registry
        tasks_from: health_check.yml

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  tags: kafka_connect
  tasks:
    - include_role:
        name: confluent.kafka_connect
        tasks_from: health_check.yml

- name: Kafta Connect Provisioning
  hosts: kafka_connect_replicator
  tags: kafka_connect_replicator
  tasks:
    - include_role:
        name: confluent.kafka_connect_replicator
        tasks_from: health_check.yml

- name: KSQL Provisioning
  hosts: ksql
  tags: ksql
  tasks:
    - include_role:
        name: confluent.ksql
        tasks_from: health_check.yml

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  tags: kafka_rest
  tasks:
    - include_role:
        name: confluent.kafka_rest
        tasks_from: health_check.yml

- name: Control Center Provisioning
  hosts: control_center
  tags: control_center
  tasks:
    - include_role:
        name: confluent.control_center
        tasks_from: health_check.yml
