---
- name: Copy Host Truststore to Host
  copy:
    src: "{{ssl_truststore_filepath}}"
    dest: "{{truststore_path}}"

- name: Copy Host Keystore to Host
  copy:
    src: "{{ssl_keystore_filepath}}"
    dest: "{{keystore_path}}"

- name: Export Certs from Keystore and Truststore
  include_tasks: export_certs_from_keystore_and_truststore.yml
  when: export_certs|bool or
        ( (secrets_protection_enabled|bool) and (rbac_enabled|bool) )
