---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Download Jolokia Jar
      get_url:
        url: http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar
        dest: "{{ jolokia_jar_url }}"
    - name: Download Jmx Exporter Jar
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
        dest: "{{ jmxexporter_jar_url }}"
