---
- name: Register if Keystore Exists
  stat:
    path: "{{keystore_path}}"
  register: keystore

- name: Register if Truststore Exists
  stat:
    path: "{{truststore_path}}"
  register: truststore

- name: Create Keystore and Truststore
  include_tasks: create_keystore_and_truststore.yml
  when: not keystore.stat.exists|bool or not truststore.stat.exists|bool or regenerate_keystore_and_truststore|bool

- name: Set Truststore and Keystore File Permissions
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0640
  loop:
    - "{{keystore_path}}"
    - "{{truststore_path}}"

- name: Set Cert and Key File Permissions
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0640
  loop:
    - "{{ca_cert_path}}"
    - "{{cert_path}}"
    - "{{key_path}}"
  when: export_certs|bool

- name: Set BCFKS Truststore and Keystore File Permissions
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0640
  loop:
    - "{{bcfks_keystore_path}}"
    - "{{bcfks_truststore_path}}"
  when: create_bouncy_castle_keystore|bool
