---
- name: Restart Schema Registry
  systemd:
    daemon_reload: true
    name: "{{schema_registry_service_name}}"
    state: restarted
  tags:
    - systemd

- name: Startup Delay
  wait_for:
    timeout: "{{ schema_registry_health_check_delay }}"
