---
# Cannot use Block/Rescue in Ansible Handlers: https://github.com/ansible/ansible/issues/14270
# Implementing try/catch logic with ignore_errors and conditionals
- name: Wait for Zookeeper Status
  shell: "{{zookeeper_health_check_command}}"
  args:
    executable: /bin/bash
  register: status
  until: status.rc == 0
  retries: 25
  delay: 5
  changed_when: false
  check_mode: false
  ignore_errors: true

- name: Wait for Zookeeper Quorum
  shell: "{{zookeeper_health_check_command}}"
  args:
    executable: /bin/bash
  register: quorum
  until: '"Latency min/avg/max:" in quorum.stdout'
  retries: 25
  delay: 5
  changed_when: false
  check_mode: false
  when: not status.failed
  ignore_errors: true

- name: Fetch Log Files and Error out
  block:
    - name: Fetch Files for Debugging Failure
      # Cannot use include_role in Ansible Handlers: https://github.com/ansible/ansible/issues/20493
      include_tasks: ../../common/tasks/fetch_logs.yml
      vars:
        service_name: "{{zookeeper_service_name}}"
        config_file: "{{zookeeper.config_file}}"
        log_dir: "{{zookeeper_service_environment_overrides.LOG_DIR}}"
        user: "{{zookeeper_user}}"
        group: "{{zookeeper_group}}"

    - name: Fail Provisioning
      fail:
        msg: Health checks failed. Review exported files.
  when: status.failed or quorum.failed
