---
namespace: confluent
name: platform
version: 7.1.1
readme: README.md
authors:
  - Confluent Ansible Community (https://github.com/confluentinc/cp-ansible)
description: Confluent Platform Ansible Collection
license_file: LICENSE.md
tags:
  - confluent
  - kafka
dependencies: {}
repository: https://github.com/confluentinc/cp-ansible
documentation: https://docs.confluent.io/ansible/current/overview.html
homepage: https://github.com/confluentinc/cp-ansible
issues: https://github.com/confluentinc/cp-ansible/issues
