---
- name: "Create User: {{ldap_user}} Config file"
  template:
    src: user.ldif.j2
    dest: "/tmp/{{ldap_user}}.ldif"

- name: "Create User: {{ldap_user}}"
  shell: "ldapadd -x -D 'cn=ldapadm,dc={{ldap_dc}},dc={{ldap_dc_extension}}' -f /tmp/{{ldap_user}}.ldif -w {{ldap_admin_password}}"

- name: "Set Password for User: {{ldap_user}}"
  shell: "ldappasswd -s {{ldap_user_password}} -D 'cn=ldapadm,dc={{ldap_dc}},dc={{ldap_dc_extension}}' -x 'uid={{ldap_user}},ou={{ldap_rbac_group}},dc={{ldap_dc}},dc={{ldap_dc_extension}}' -w {{ldap_admin_password}}"
